name: lokamakan
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner: ^2.4.9
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  change_app_package_name: ^1.3.0
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  firebase_analytics: ^10.10.5
  validatorless: ^1.2.3
  
  core:
    path: packages/core
  base:
    path: packages/base
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/chevron/
    - assets/icons/input/
    - assets/icons/message/
    - assets/icons/misc/
    - assets/icons/state/
    - assets/icons/toogle/
    - assets/images/